# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading


  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



### 2. Create a random tensor with shape `(7, 7)`.


In [44]:
# Import torch
import torch

# Create random tensor
A = torch.rand(7,7)
A

tensor([[0.0731, 0.9699, 0.1078, 0.8829, 0.4132, 0.7572, 0.6948],
        [0.5209, 0.5932, 0.8797, 0.6286, 0.7653, 0.1132, 0.8559],
        [0.6721, 0.6267, 0.5691, 0.7437, 0.9592, 0.3887, 0.2214],
        [0.3742, 0.1953, 0.7405, 0.2529, 0.2332, 0.9314, 0.9575],
        [0.5575, 0.4134, 0.4355, 0.7369, 0.0331, 0.0914, 0.8994],
        [0.9936, 0.4703, 0.1049, 0.5137, 0.2674, 0.4990, 0.7447],
        [0.7213, 0.4414, 0.5550, 0.6361, 0.1081, 0.3305, 0.5196]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [45]:
# Create another random tensor
B = torch.rand(1,7)
B
# Perform matrix multiplication
torch.matmul(A, B.T)

tensor([[2.0348],
        [2.4466],
        [2.0632],
        [1.9728],
        [1.8481],
        [1.6848],
        [1.7088]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [21]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
# Create two random tensors
random_A = torch.rand(7,7)
random_B = torch.rand(1,7)
print(random_A)
print(random_B)
# Matrix multiply tensors
torch.matmul(random_A,random_B.T),torch.matmul(random_A,random_B.T).shape


tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])


(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [26]:
# Set random seed on the GPU
if torch.cuda.is_available():
    print("CUDA is available")
    # Set random seed on the GPU
    torch.cuda.manual_seed(1234)
else:
    print("CUDA is not available")


CUDA is available



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [30]:
# Set random seed
RANDOM_SEED = 1234
torch.cuda.manual_seed(RANDOM_SEED)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Device: {device}')
# Create two random tensors on GPU
Random_A = torch.rand(2,3).to(device)
Random_B = torch.rand(2,3).to(device)
print(Random_A)
print(Random_B)

Device: cuda
tensor([[0.8102, 0.9801, 0.1147],
        [0.3168, 0.6965, 0.9143]], device='cuda:0')
tensor([[0.9351, 0.9412, 0.5995],
        [0.0652, 0.5460, 0.1872]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [32]:
# Perform matmul on tensor_A and tensor_B
torch.matmul(Random_A,Random_B.T),torch.matmul(Random_A,Random_B.T).shape

(tensor([[1.7488, 0.6094],
         [1.4999, 0.5721]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [36]:
# Find max
print(torch.max(Random_A))
print(torch.max(Random_B))
# Find min
print(torch.min(Random_A))
print(torch.min(Random_B))

tensor(0.9801, device='cuda:0')
tensor(0.9412, device='cuda:0')
tensor(0.1147, device='cuda:0')
tensor(0.0652, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [37]:
# Find arg max
print(torch.argmax(Random_A))
print(torch.argmax(Random_B))
# Find arg min
print(torch.argmin(Random_A))
print(torch.argmin(Random_B))

tensor(1, device='cuda:0')
tensor(1, device='cuda:0')
tensor(2, device='cuda:0')
tensor(3, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [48]:
# Set seed
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)

# Create random tensor
random_tensor = torch.rand(1,1,1,10)
print(random_tensor,random_tensor.shape)
# Remove single dimensions
remove_dimensions = torch.squeeze(random_tensor)

# Print out tensors and their shapes
print(remove_dimensions, remove_dimensions.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
